config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :kpi_settings
match '/kpi', to: 'kpi#index', via: [:get]
match '/kpi/:action', controller: 'kpi', via: [:get, :post]

app/models/kpi_setting.rb
class KpiSetting < ActiveRecord::Base
  validates_presence_of :effective_date,  :h_task_before_deadline,  :h_task_on_deadline,
                        :h_task_after_deadline,  :n_task_before_deadline,  :n_task_on_deadline,
                        :n_task_after_deadline,  :l_task_before_deadline,  :l_task_on_deadline,
                        :l_task_after_deadline,
                        :low_utilization, :high_utilization
  validates_uniqueness_of :effective_date

  def for_high_utilization
    {
        before: h_task_before_deadline,
        on: h_task_on_deadline,
        after: h_task_after_deadline
    }
  end

  def for_normal_utilization
    {
        before: n_task_before_deadline,
        on: n_task_on_deadline,
        after: n_task_after_deadline
    }
  end

  def for_low_utilization
    {
        before: l_task_before_deadline,
        on: l_task_on_deadline,
        after: l_task_after_deadline
    }
  end

  def self.default
    new(:h_task_before_deadline=> 6,  :h_task_on_deadline=> 4,  :h_task_after_deadline=> 0,
        :n_task_before_deadline=> 5,  :n_task_on_deadline=> 3,  :n_task_after_deadline=> 0,
        :l_task_before_deadline=> 4,  :l_task_on_deadline=> 2,  :l_task_after_deadline=> 0,
        :low_utilization=> 40,        :normal_utilization=> 60, :high_utilization=> 60,
        :time_record_point=> 2,
        profitability_point: 1,
        learning_point: 4, certification_point: 3,
        reopened_ticket_point: 2, closed_ticket_point: 2,
        one_day_started_ticket_point: 4,  two_day_started_ticket_point: 2, three_day_started_ticket_point: 1,
        presales_point: 6)
  end


end

app/controllers/kpi_settings_controller.rb
class KpiSettingsController < ApplicationController
  before_action :set_kpi_setting, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  # GET /kpi_settings
  def index
    @kpi_settings = KpiSetting.all
  end

  # GET /kpi_settings/1
  def show
  end

  # GET /kpi_settings/new
  def new
    @kpi_setting = KpiSetting.default
  end

  # GET /kpi_settings/1/edit
  def edit
  end

  # POST /kpi_settings
  def create
    @kpi_setting = KpiSetting.new(kpi_setting_params)

    if @kpi_setting.save
      redirect_to @kpi_setting, notice: 'Kpi setting was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /kpi_settings/1
  def update
    if @kpi_setting.update(kpi_setting_params)
      redirect_to @kpi_setting, notice: 'Kpi setting was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /kpi_settings/1
  def destroy
    @kpi_setting.destroy
    redirect_to kpi_settings_url, notice: 'Kpi setting was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kpi_setting
      @kpi_setting = KpiSetting.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def kpi_setting_params
      params.require(:kpi_setting).permit!
    end
end

app/views/kpi_settings/_form.html.erb
<%= form_for(@kpi_setting) do |f| %>
    <% if @kpi_setting.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@kpi_setting.errors.count, "error") %> prohibited this kpi_setting from being saved:</h2>

          <ul>
            <% @kpi_setting.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label 'Effective Date' %><br>
      <%= f.date_select :effective_date %>
    </div>
    <fieldset>
      <legend>Promptness</legend>
      <div class="container">
        <div class="splitcontent">

          <div style="width: 33%; float:left">
            <h3>High Utilization</h3>
            <div class="field">
              <%= f.label :high_utilization %> (MIN High-Beginning => 100%)<br>
              <%= f.number_field :high_utilization %>
            </div>
            <div class="field">
              <%= f.label :task_finished_before_deadline %><br>
              <%= f.number_field :h_task_before_deadline %>
            </div>
            <div class="field">
              <%= f.label :task_finished_on_deadline %><br>
              <%= f.number_field :h_task_on_deadline %>
            </div>
            <div class="field">
              <%= f.label :task_finished_after_deadline %><br>
              <%= f.number_field :h_task_after_deadline %>
            </div>

          </div>
          <div style="width: 33%; float:left;">


            <h3 >Normal Utilization</h3>
            <div class="field" style="margin-top: 58px">
              <%= f.label :task_finished_before_deadline %><br>
              <%= f.number_field :n_task_before_deadline %>
            </div>
            <div class="field">
              <%= f.label :task_finished_on_deadline %><br>
              <%= f.number_field :n_task_on_deadline %>
            </div>
            <div class="field">
              <%= f.label :task_finished_after_deadline %><br>
              <%= f.number_field :n_task_after_deadline %>
            </div>

          </div>

          <div style="width: 33%; float:left">
            <h3 >Low Utilization</h3>
            <div class="field">
              <%= f.label :low_utilization %>(0% => MAX low utilization) <br>
              <%= f.number_field :low_utilization %>
            </div>
            <div class="field">
              <%= f.label :task_finished_before_deadline %><br>
              <%= f.number_field :l_task_before_deadline %>
            </div>
            <div class="field">
              <%= f.label :task_finished_on_deadline %><br>
              <%= f.number_field :l_task_on_deadline %>
            </div>
            <div class="field">
              <%= f.label :task_finished_after_deadline %><br>
              <%= f.number_field :l_task_after_deadline %>
            </div>
          </div>

        </div>

      </div>
    </fieldset>
    <fieldset>
      <legend>Time Recording Precision</legend>
      <div class="container">
        <div class="splitcontent">
          <div class="field">
            <%= f.label :time_record_point %><br>
            <%= f.number_field :time_record_point %>
          </div>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Presales</legend>
      <div class="container">
        <div class="splitcontent">
          <div class="field">
            <%= f.label 'Presales points per task' %><br>
            <%= f.number_field :presales_point %>
          </div>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Learning & Certification</legend>
      <div class="container">
        <div class="splitcontent">
          <div class="field">
            <%= f.label 'Learning points per 10 hours' %><br>
            <%= f.number_field :learning_point %>
          </div>
          <div class="field">
            <%= f.label 'Certification points per exam' %><br>
            <%= f.number_field :certification_point %>
          </div>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Profitability</legend>
      <div class="container">
        <div class="splitcontent">
          <div class="field">
            <%= f.label 'Profitability points ( > 25% )' %><br>
            <%= f.number_field :profitability_point %>
          </div>
        <div class="field">
            <%= f.label 'Profitability points ( < 25% )' %><br>
            <%= f.number_field :profitability_point_inf %>
          </div>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Support</legend>
      <div class="container">
        <div class="splitcontent">
          <div class="field">
            <%= f.label 'Reopened Tickets points (< 5%)' %><br>
            <%= f.number_field :reopened_ticket_point %>
          </div>
        <div class="field">
            <%= f.label 'Time to close points (avg < 7 days)' %><br>
            <%= f.number_field :closed_ticket_point %>
          </div>
        <div class="field">
            <%= f.label 'Time To Start ( < 1 day)' %><br>
            <%= f.number_field :one_day_started_ticket_point %>
          </div>
        <div class="field">
            <%= f.label 'Time To Start ( < 2 days)' %><br>
            <%= f.number_field :two_day_started_ticket_point %>
          </div>
        <div class="field">
            <%= f.label 'Time To Start ( < 3 days)' %><br>
            <%= f.number_field :three_day_started_ticket_point %>
          </div>
        </div>
      </div>
    </fieldset>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/kpi_settings/edit.html.erb
<h1>Editing KPI Setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @kpi_setting %> |
<%= link_to 'Back', kpi_settings_path %>

app/views/kpi_settings/index.html.erb
<div class="contextual">
  <%= link_to 'New Kpi setting', new_kpi_setting_path, class: 'icon icon-add' %>
</div>
<h2>Listing KPIs Settings</h2>
<div style="overflow-x: scroll">
  <table class="table list">
    <thead>
    <tr>
      <th></th>
      <th colspan="3">High Utilization</th>
      <th colspan="3">Normal Utilization</th>
      <th colspan="3">Low Utilization</th>
      <th>Time Record POINT</th>
      <th>Presale POINTS/Task</th>
      <th colspan="3"></th>
    </tr>
    <tr>
      <th>Effective date</th>
      <th>Task finished before deadline</th>
      <th>Task finished on deadline</th>
      <th>Task finished after deadline</th>
      <th>Task finished before deadline</th>
      <th>Task finished on deadline</th>
      <th>Task finished after deadline</th>
      <th>Task finished before deadline</th>
      <th>Task finished on deadline</th>
      <th>Task finished after deadline</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @kpi_settings.each_with_index do |kpi_setting, index| %>
        <tr>
          <td><%= kpi_setting.effective_date %></td>
          <td><%= kpi_setting.h_task_before_deadline %></td>
          <td><%= kpi_setting.h_task_on_deadline %></td>
          <td><%= kpi_setting.h_task_after_deadline %></td>
          <td><%= kpi_setting.n_task_before_deadline %></td>
          <td><%= kpi_setting.n_task_on_deadline %></td>
          <td><%= kpi_setting.n_task_after_deadline %></td>
          <td><%= kpi_setting.l_task_before_deadline %></td>
          <td><%= kpi_setting.l_task_on_deadline %></td>
          <td><%= kpi_setting.l_task_after_deadline %></td>
          <td><%= kpi_setting.time_record_point %></td>
          <td><%= kpi_setting.presales_point %></td>
          <td><%= link_to 'Show', kpi_setting %></td>
          <td><%= (index == @kpi_settings.count - 1) ?  link_to( 'Edit', edit_kpi_setting_path(kpi_setting)) : '' %></td>
          <td><%= (index == @kpi_settings.count - 1) ?   link_to( 'Delete', kpi_setting, method: :delete, data: { confirm: 'Are you sure?' }) : '' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/kpi_settings/new.html.erb
<div class="contextual"><%= link_to 'Back', kpi_settings_path %></div>
<h2>New KPI Setting</h2>

<%= render 'form' %>

app/views/kpi_settings/show.html.erb
<div class="contextual">
  <%= link_to l(:button_back), kpi_settings_path,  class: 'icon icon-back' %>
  <%= link_to l(:button_edit), edit_kpi_setting_path(@kpi_setting),  class: 'icon icon-edit' if @kpi_setting.id == KpiSetting.last.id %>
  <%= link_to l(:button_delete), kpi_settings_path, method: :delete, data: { confirm: 'Are you sure?' } ,  class: 'icon icon-del' if @kpi_setting.id == KpiSetting.last.id %>
</div>
<h2>KPIs Setting </h2>
<div class="splitcontent box">
  <p>
    <strong>Effective date:</strong>
    <%= @kpi_setting.effective_date %>
  </p>

  <div style="width: 33%; float:left">
    <h3>High Utilization</h3>
    <p>
      <strong>High utilization</strong>
      <%= @kpi_setting.high_utilization %>
    </p>

    <p>
      <strong>Task finished before deadline:</strong>
      <%= @kpi_setting.h_task_before_deadline %>
    </p>

    <p>
      <strong>Task finished on deadline:</strong>
      <%= @kpi_setting.h_task_on_deadline %>
    </p>

    <p>
      <strong>Task finished after deadline:</strong>
      <%= @kpi_setting.h_task_after_deadline %>
    </p>


  </div>
  <div style="width: 33%; float:left;">


    <h3 >Normal Utilization</h3>

    <p style="margin-top: 40px">
      <strong>Task finished before deadline:</strong>
      <%= @kpi_setting.n_task_before_deadline %>
    </p>

    <p>
      <strong>Task finished on deadline:</strong>
      <%= @kpi_setting.n_task_on_deadline %>
    </p>

    <p>
      <strong>Task finished after deadline:</strong>
      <%= @kpi_setting.n_task_after_deadline %>
    </p>


  </div>

  <div style="width: 33%; float:left">
    <h3 >Low Utilization</h3>
    <p>
      <strong>Low utilization</strong>
      <%= @kpi_setting.low_utilization %>
    </p>


    <p>
      <strong>Task finished before deadline:</strong>
      <%= @kpi_setting.l_task_before_deadline %>
    </p>

    <p>
      <strong>Task finished on deadline:</strong>
      <%= @kpi_setting.l_task_on_deadline %>
    </p>

    <p>
      <strong>Task finished after deadline:</strong>
      <%= @kpi_setting.l_task_after_deadline %>
    </p>
  </div>


</div>
<hr/>
<p>
  <strong>Time Record Points:</strong>
  <%= @kpi_setting.time_record_point %>
</p>
<p>
  <strong>Presales Points per Task:</strong>
  <%= @kpi_setting.presales_point %>
</p>


<hr/>
<p>
  <strong>Learning Points:</strong>
  <%= @kpi_setting.learning_point %>
</p>
<p>
  <strong>Certification Point:</strong>
  <%= @kpi_setting.certification_point %>
</p>

<hr/>
<p>
  <strong>Profitability Points ( > 25%):</strong>
  <%= @kpi_setting.profitability_point %>
</p>

<p>
  <strong>Profitability Points (< 25% ):</strong>
  <%= @kpi_setting.profitability_point_inf %>
</p>

<hr/>
<p>
  <strong>Reopened Tickets points (< 5%)</strong>
  <%= @kpi_setting.reopened_ticket_point %>
</p>
<p>
  <strong>Closed Tickets points (avg < 7 days)</strong>
  <%= @kpi_setting.closed_ticket_point %>
</p>
<p>
  <strong>Time To Start tickets points ( < 1 day)</strong>
  <%= @kpi_setting.one_day_started_ticket_point %>
</p>
<p>
  <strong>Time To Start tickets points ( < 2 days)</strong>
  <%= @kpi_setting.two_day_started_ticket_point %>
</p>
<p>
  <strong>Time To Start tickets points ( < 3 days)</strong>
  <%= @kpi_setting.three_day_started_ticket_point %>

</p>